name: Publish Docker image
on:
  push:
    branches:
      - master 
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Docker meta
        id: meta
        uses: crazy-max/ghaction-docker-meta@v2
        with:          
          images: mgkaiser/mssqltest1
          flavor: latest=false
          tags: type=raw,enable=true,prefix=Build-,value=${{ github.run_number }}
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .  
          push: true        
          tags: ${{ steps.meta.outputs.tags }}      
          labels: ${{ steps.meta.outputs.labels }}    
      - name: Update the helm chart
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TAGS: ${{ github.run_number }}
          API_TOKEN: ${{ secrets.API_TOKEN }}
        run: |
          echo "Step 1"
          git clone https://mkaiserincomm:$GITHUB_TOKEN@github.com/mkaiserincomm/mssqltest1-helm
          echo "Step 2"          
          git config --global user.email "mkaiser@incomm.com"
          echo "Step 3"
          git config --global user.name "Michael Kaiser"
          echo "Step 4"
          cd mssqltest1-helm
          echo "Step 5"
          cat ./values.yaml | sed 's/tag: \"latest\"/tag: \"Build-'$GITHUB_TAGS'\"/' > ./charts/mssqltest1/values.yaml          
          echo "Step 6"
          git add ./charts/mssqltest1/values.yaml
          echo "Step 7"
          git commit -m "Updated build number"
          echo "Step 8"
          git push --set-upstream https://mkaiserincomm:$API_TOKEN@github.com/mkaiserincomm/mssqltest1-helm

